/*
   ________  ______________   ________  _______   _____________    ___    ____  ______   _    ______________  __   ________  ____  ____  ____  ____  ____  ____  ____  ____  ____  ____  ____  ____  ____  ____  ____  ____  ____  ____  ____  ____  ____  ____  ____  ______________
  / ____/ / / /_  __/ ____/  /_  __/ / / /  _/ | / / ____/ ___/   /   |  / __ \/ ____/  | |  / / ____/ __ \ \/ /  / ____/ / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / /_  __/ ____/
 / /   / / / / / / / __/      / / / /_/ // //  |/ / / __ \__ \   / /| | / /_/ / __/     | | / / __/ / /_/ /\  /  / /   / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / __/   
/ /___/ /_/ / / / / /___     / / / __  // // /|  / /_/ /___/ /  / ___ |/ _, _/ /___     | |/ / /___/ _, _/ / /  / /___/ /_/ / /_/ / /_/ / /_/ / /_/ / /_/ / /_/ / /_/ / /_/ / /_/ / /_/ / /_/ / /_/ / /_/ / /_/ / /_/ / /_/ / /_/ / /_/ / /_/ / /_/ / /_/ / /_/ / /_/ / / / / /___   
\____/\____/ /_/ /_____/    /_/ /_/ /_/___/_/ |_/\____//____/  /_/  |_/_/ |_/_____/     |___/_____/_/ |_| /_/   \____/\____/\____/\____/\____/\____/\____/\____/\____/\____/\____/\____/\____/\____/\____/\____/\____/\____/\____/\____/\____/\____/\____/\____/\____/ /_/ /_____/   
                                                                                                                                                                                                                                                                                     
*/

/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */
#include <bits/stdc++.h>
/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE *//* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE *//* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE *//* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE *//* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE *//* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE *//* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */
typedef int CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE;
#define CUUUUUUUUUUUUUTE for
                                /* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */                                                                                                #define CUTE X
#define CUUUUUUUUUUUUUUUUUUUUUTE cout
    #define CUUUUUUUUUUUUuuuuuuUUUUUTE " ";
#define cuuuuute main /* CUUUUUUUUUUUUTE */ 
              using namespace std; CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE cuuuuute() {
                #define CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE if
      #define CUUUUUTE CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE
  CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE /* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */ CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE; cin >> CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE; CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE[CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE][CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE]; CUUUUUUUUUUUUUTE(CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE cute = 0; cute < CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE; cute++)
            /* CUUUUUUUUUUUUTE */       CUUUUUUUUUUUUUTE(CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE CUTEEEEEEE = 0; CUTEEEEEEE < CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE; CUTEEEEEEE++)
      cin >> CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE /* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */ [cute][CUTEEEEEEE]; {{{{}}}}  /* CUUUUUUUUUUUUTE */ 
#define CUUUUTE min /* CUUUUUUUUUUUUTE */ 
    CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE CUUUUUUUUUUUUUUTE = CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE[0][0];
                    CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE CUUUUUUUUUUUUTE =  /* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */ CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE[0][CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE - 1];
  CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE CUUUTE = CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE[CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE - 1][0];
                                  /* CUUUUUUUUUUUUTE */ /* CUUUUUUUUUUUUTE */ /* CUUUUUUUUUUUUTE */ /* CUUUUUUUUUUUUTE */       CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE CUUUUUUTE = CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE[CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE - 1][CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE - 1];
                {{{{{}}}}}                       CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE =  
                                  CUUUUTE({CUUUUUUUUUUUUUUTE, CUUUUUUUUUUUUTE, CUUUTE, CUUUUUUTE});
{{{{{{{{{{{{{{{{{{}}}}}}}}}}}}}}}}}} 

/*
       _..._                                           
    .-'_..._''.                                        
  .' .'      '.\                        __.....__      
 / .'                               .-''         '.    
. '                           .|   /     .-''"'-.  `.  
| |                         .' |_ /     /________\   \ 
| |               _    _  .'     ||                  | 
. '              | '  / |'--.  .-'\    .-------------' 
 \ '.          ..' | .' |   |  |   \    '-.____...---. 
  '. `._____.-'//  | /  |   |  |    `.             .'  
    `-.______ /|   `'.  |   |  '.'    `''-...... -'    
             ` '   .'|  '/  |   /                      
                `-'  `--'   `'-'                       
*/
#define CUUUUUUUUUUUTE "\n" /* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */
   /* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */ CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE(CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE ==  /* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */ CUUUUUUUUUUUUUUTE)
    CUUUUUUUUUUUUUTE(CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE CUTE = 0; CUTE <= /* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */ CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE - 1; CUTE++) { CUUUUUUUUUUUUUTE(CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE CUUUUUTE = 0; CUUUUUTE <= CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE - 1; CUUUUUTE++)
        CUUUUUUUUUUUUUUUUUUUUUTE /* CUUUUUUUUUUUUTE */  << CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE[CUTE][CUUUUUTE] << CUUUUUUUUUUUUuuuuuuUUUUUTE;
            CUUUUUUUUUUUUUUUUUUUUUTE << CUUUUUUUUUUUTE;/* CUUUUUUUUUUUUTE */ /* CUUUUUUUUUUUUTE */ /* CUUUUUUUUUUUUTE */ /* CUUUUUUUUUUUUTE */ /* CUUUUUUUUUUUUTE */ 
      } /* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */ CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE(CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE == CUUUUUUUUUUUUTE)
                          CUUUUUUUUUUUUUTE(CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE CUTE = CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE - 1; CUTE >= 0; CUTE--) {
                CUUUUUUUUUUUUUTE(CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE CUUUUUTE = 0; CUUUUUTE < CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE; CUUUUUTE++)
          CUUUUUUUUUUUUUUUUUUUUUTE << CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE[CUUUUUTE][CUTE] << CUUUUUUUUUUUUuuuuuuUUUUUTE;
                       CUUUUUUUUUUUUUUUUUUUUUTE << CUUUUUUUUUUUTE;/* CUUUUUUUUUUUUTE */ 
    } CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE(CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE == CUUUUUUTE) {
   /* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */  CUUUUUUUUUUUUUTE(CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE  /* CUUUUUUUUUUUUTE */  /* CUUUUUUUUUUUUTE */  /* CUUUUUUUUUUUUTE */ CUTE = CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE - 1; CUTE >= 0; CUTE--) {
      CUUUUUUUUUUUUUTE(CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE CUUUUUTE = CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE - 1; CUUUUUTE >= 0; CUUUUUTE--){
    /* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */     CUUUUUUUUUUUUUUUUUUUUUTE << CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE[CUTE][CUUUUUTE] << CUUUUUUUUUUUUuuuuuuUUUUUTE;
          } {} {} {{{{{{{{{{{{{}}}}}}}}}}}}}
      CUUUUUUUUUUUUUUUUUUUUUTE << CUUUUUUUUUUUTE;/* CUUUUUUUUUUUUTE */ /* CUUUUUUUUUUUUTE */ /* CUUUUUUUUUUUUTE */ /* CUUUUUUUUUUUUTE */ 
    } } CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE(CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE == CUUUTE)
    CUUUUUUUUUUUUUTE(CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE CUTE = 0; CUTE <= CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE - 1; CUTE++) {
                                        CUUUUUUUUUUUUUTE(CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE CUUUUUTE = CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE - 1; CUUUUUTE >= 0; CUUUUUTE--)
        CUUUUUUUUUUUUUUUUUUUUUTE << CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE[CUUUUUTE][CUTE] << CUUUUUUUUUUUUuuuuuuUUUUUTE;
      CUUUUUUUUUUUUUUUUUUUUUTE << CUUUUUUUUUUUTE;
    }
}
/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE *//* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE *//* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */
/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE *//* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE *//* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */
/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */
/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */
/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */
/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */
/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */
/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */
/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE *//* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */
/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */
/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE *//* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE *//* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE *//* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE *//* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */
/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */
/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */
/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */
/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */
/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */
/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */

/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */
/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */
/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */
/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */
/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */
/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE *//* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */
/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */
/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */
/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */

/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */

/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE *//* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */

/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */
/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */
/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */

/* CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUTE */


/*
   _,.----.                                                   ,--.--------.    ,----.  
 .' .' -   \ .--.-. .-.-..--.-. .-.-..--.-. .-.-..--.-. .-.-./==/,  -   , -\,-.--` , \ 
/==/  ,  ,-'/==/ -|/=/  /==/ -|/=/  /==/ -|/=/  /==/ -|/=/  |\==\.-.  - ,-./==|-  _.-` 
|==|-   |  .|==| ,||=| -|==| ,||=| -|==| ,||=| -|==| ,||=| -| `--`\==\- \  |==|   `.-. 
|==|_   `-' \==|- | =/  |==|- | =/  |==|- | =/  |==|- | =/  |      \==\_ \/==/_ ,    / 
|==|   _  , |==|,  \/ - |==|,  \/ - |==|,  \/ - |==|,  \/ - |      |==|- ||==|    .-'  
\==\.       /==|-   ,   /==|-   ,   /==|-   ,   /==|-   ,   /      |==|, ||==|_  ,`-._ 
 `-.`.___.-'/==/ , _  .'/==/ , _  .'/==/ , _  .'/==/ , _  .'       /==/ -//==/ ,     / 
            `--`..---'  `--`..---'  `--`..---'  `--`..---'         `--`--``--`-----``  
            */